// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SeedGalleryPhoto,
} from "./types";

export default {
  orgId: __t.u64(),
  picture: __t.string(),
  pictureSmall: __t.string(),
  pictureUrl: __t.string(),
  get gallery() {
    return __t.array(SeedGalleryPhoto);
  },
  adminSecret: __t.string(),
};
