// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit 31fd1c8c3346dfec38dfcc2e89c2ecf457cf26ff).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendRequestReducer from "./accept_friend_request_reducer";
import AcceptOrgMemberReducer from "./accept_org_member_reducer";
import AdminDeleteProfileReducer from "./admin_delete_profile_reducer";
import AdminSetProReducer from "./admin_set_pro_reducer";
import AdminUpdateProfileReducer from "./admin_update_profile_reducer";
import CancelFriendRequestReducer from "./cancel_friend_request_reducer";
import ClaimProfileReducer from "./claim_profile_reducer";
import CreateOrganizationReducer from "./create_organization_reducer";
import CreateProfileReducer from "./create_profile_reducer";
import CreateStoryPostReducer from "./create_story_post_reducer";
import DeclineFriendRequestReducer from "./decline_friend_request_reducer";
import DeclineOrgMemberReducer from "./decline_org_member_reducer";
import DeleteStoryPostReducer from "./delete_story_post_reducer";
import DemoteCoLeaderReducer from "./demote_co_leader_reducer";
import FollowReducer from "./follow_reducer";
import ManualCreateProfileReducer from "./manual_create_profile_reducer";
import PromoteToCoLeaderReducer from "./promote_to_co_leader_reducer";
import RefreshFeedReducer from "./refresh_feed_reducer";
import RegisterPushSubscriptionReducer from "./register_push_subscription_reducer";
import RemoveOrgMemberReducer from "./remove_org_member_reducer";
import ResolveNotificationReducer from "./resolve_notification_reducer";
import SendDirectMessageReducer from "./send_direct_message_reducer";
import SendFriendRequestReducer from "./send_friend_request_reducer";
import SendOrgMemberRequestReducer from "./send_org_member_request_reducer";
import SendOrgMessageReducer from "./send_org_message_reducer";
import TransferLeadershipReducer from "./transfer_leadership_reducer";
import UnfollowReducer from "./unfollow_reducer";
import UnfriendReducer from "./unfriend_reducer";
import UnregisterPushSubscriptionReducer from "./unregister_push_subscription_reducer";
import UpdateFeedScrollPositionReducer from "./update_feed_scroll_position_reducer";
import UpdateOrganizationReducer from "./update_organization_reducer";
import UpdateProfileReducer from "./update_profile_reducer";
import UpgradeToProReducer from "./upgrade_to_pro_reducer";

// Import all procedure arg schemas
import * as CheckDiditVerificationProcedure from "./check_didit_verification_procedure";
import * as CreateVerifiedProfileProcedure from "./create_verified_profile_procedure";
import * as InitiateDiditVerificationProcedure from "./initiate_didit_verification_procedure";

// Import all table schema definitions
import FollowingRow from "./following_table";
import FriendRequestRow from "./friend_request_table";
import FriendshipRow from "./friendship_table";
import MessageRow from "./message_table";
import MyFeedRow from "./my_feed_table";
import NotificationRow from "./notification_table";
import OrgMemberRequestRow from "./org_member_request_table";
import OrganizationRow from "./organization_table";
import OrganizationMemberRow from "./organization_member_table";
import StoryPostRow from "./story_post_table";
import UserProfileRow from "./user_profile_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  following: __table({
    name: 'following',
    indexes: [
    ],
    constraints: [
    ],
  }, FollowingRow),
  friend_request: __table({
    name: 'friend_request',
    indexes: [
      { accessor: 'id', name: 'friend_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'friend_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FriendRequestRow),
  friendship: __table({
    name: 'friendship',
    indexes: [
      { accessor: 'id', name: 'friendship_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'friendship_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FriendshipRow),
  message: __table({
    name: 'message',
    indexes: [
      { accessor: 'created_at', name: 'message_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessageRow),
  notification: __table({
    name: 'notification',
    indexes: [
      { accessor: 'id', name: 'notification_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'notification_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NotificationRow),
  org_member_request: __table({
    name: 'org_member_request',
    indexes: [
      { accessor: 'id', name: 'org_member_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'org_member_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrgMemberRequestRow),
  organization: __table({
    name: 'organization',
    indexes: [
      { accessor: 'id', name: 'organization_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'organization_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrganizationRow),
  organization_member: __table({
    name: 'organization_member',
    indexes: [
    ],
    constraints: [
    ],
  }, OrganizationMemberRow),
  story_post: __table({
    name: 'story_post',
    indexes: [
      { accessor: 'created_at', name: 'story_post_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'story_post_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'story_post_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StoryPostRow),
  user_profile: __table({
    name: 'user_profile',
    indexes: [
      { accessor: 'email', name: 'user_profile_email_idx_btree', algorithm: 'btree', columns: [
        'email',
      ] },
      { accessor: 'identity', name: 'user_profile_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_profile_email_key', constraint: 'unique', columns: ['email'] },
      { name: 'user_profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserProfileRow),
  my_feed: __table({
    name: 'my_feed',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFeedRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_friend_request", AcceptFriendRequestReducer),
  __reducerSchema("accept_org_member", AcceptOrgMemberReducer),
  __reducerSchema("admin_delete_profile", AdminDeleteProfileReducer),
  __reducerSchema("admin_set_pro", AdminSetProReducer),
  __reducerSchema("admin_update_profile", AdminUpdateProfileReducer),
  __reducerSchema("cancel_friend_request", CancelFriendRequestReducer),
  __reducerSchema("claim_profile", ClaimProfileReducer),
  __reducerSchema("create_organization", CreateOrganizationReducer),
  __reducerSchema("create_profile", CreateProfileReducer),
  __reducerSchema("create_story_post", CreateStoryPostReducer),
  __reducerSchema("decline_friend_request", DeclineFriendRequestReducer),
  __reducerSchema("decline_org_member", DeclineOrgMemberReducer),
  __reducerSchema("delete_story_post", DeleteStoryPostReducer),
  __reducerSchema("demote_co_leader", DemoteCoLeaderReducer),
  __reducerSchema("follow", FollowReducer),
  __reducerSchema("manual_create_profile", ManualCreateProfileReducer),
  __reducerSchema("promote_to_co_leader", PromoteToCoLeaderReducer),
  __reducerSchema("refresh_feed", RefreshFeedReducer),
  __reducerSchema("register_push_subscription", RegisterPushSubscriptionReducer),
  __reducerSchema("remove_org_member", RemoveOrgMemberReducer),
  __reducerSchema("resolve_notification", ResolveNotificationReducer),
  __reducerSchema("send_direct_message", SendDirectMessageReducer),
  __reducerSchema("send_friend_request", SendFriendRequestReducer),
  __reducerSchema("send_org_member_request", SendOrgMemberRequestReducer),
  __reducerSchema("send_org_message", SendOrgMessageReducer),
  __reducerSchema("transfer_leadership", TransferLeadershipReducer),
  __reducerSchema("unfollow", UnfollowReducer),
  __reducerSchema("unfriend", UnfriendReducer),
  __reducerSchema("unregister_push_subscription", UnregisterPushSubscriptionReducer),
  __reducerSchema("update_feed_scroll_position", UpdateFeedScrollPositionReducer),
  __reducerSchema("update_organization", UpdateOrganizationReducer),
  __reducerSchema("update_profile", UpdateProfileReducer),
  __reducerSchema("upgrade_to_pro", UpgradeToProReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("check_didit_verification", CheckDiditVerificationProcedure.params, CheckDiditVerificationProcedure.returnType),
  __procedureSchema("create_verified_profile", CreateVerifiedProfileProcedure.params, CreateVerifiedProfileProcedure.returnType),
  __procedureSchema("initiate_didit_verification", InitiateDiditVerificationProcedure.params, InitiateDiditVerificationProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

