// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  orgId: __t.u64().name("org_id"),
  name: __t.string(),
  picture: __t.string(),
  pictureSmall: __t.option(__t.string()).name("picture_small"),
  pictureUrl: __t.option(__t.string()).name("picture_url"),
  pictureSource: __t.option(__t.string()).name("picture_source"),
  city: __t.string(),
  description: __t.string(),
  gender: __t.option(__t.string()),
  hideMembers: __t.bool().name("hide_members"),
  leaderIdentity: __t.identity().name("leader_identity"),
  createdAt: __t.timestamp().name("created_at"),
  isPro: __t.bool().name("is_pro"),
  ratingAvg: __t.f64().name("rating_avg"),
  ratingCount: __t.u64().name("rating_count"),
  myRole: __t.string().name("my_role"),
});
