// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CheckDiditResult = __t.object("CheckDiditResult", {
  success: __t.bool(),
  fullName: __t.option(__t.string()),
  selfieImage: __t.option(__t.string()),
  status: __t.option(__t.string()),
  error: __t.option(__t.string()),
});
export type CheckDiditResult = __Infer<typeof CheckDiditResult>;

export const CreateVerifiedProfileResult = __t.object("CreateVerifiedProfileResult", {
  success: __t.bool(),
  error: __t.option(__t.string()),
});
export type CreateVerifiedProfileResult = __Infer<typeof CreateVerifiedProfileResult>;

export const FeedPosition = __t.object("FeedPosition", {
  identity: __t.identity(),
  lastReadAt: __t.timestamp(),
  lastFeedLoadAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FeedPosition = __Infer<typeof FeedPosition>;

export const FeedStory = __t.object("FeedStory", {
  id: __t.u64(),
  profileOwnerIdentity: __t.identity(),
  posterIdentity: __t.identity(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  createdAt: __t.timestamp(),
  posterName: __t.string(),
  posterPicture: __t.string(),
  profileOwnerName: __t.string(),
  profileOwnerPicture: __t.string(),
  actingAsOrgId: __t.option(__t.u64()),
  actingAsOrgName: __t.option(__t.string()),
  actingAsOrgPicture: __t.option(__t.string()),
});
export type FeedStory = __Infer<typeof FeedStory>;

export const Following = __t.object("Following", {
  followerIdentity: __t.identity(),
  followingIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Following = __Infer<typeof Following>;

export const FriendRequest = __t.object("FriendRequest", {
  id: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type FriendRequest = __Infer<typeof FriendRequest>;

export const Friendship = __t.object("Friendship", {
  id: __t.u64(),
  userA: __t.identity(),
  userB: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Friendship = __Infer<typeof Friendship>;

export const InitiateDiditResult = __t.object("InitiateDiditResult", {
  success: __t.bool(),
  url: __t.option(__t.string()),
  error: __t.option(__t.string()),
});
export type InitiateDiditResult = __Infer<typeof InitiateDiditResult>;

export const LastPost = __t.object("LastPost", {
  posterIdentity: __t.identity(),
  profileOwnerIdentity: __t.identity(),
  lastPostedAt: __t.timestamp(),
});
export type LastPost = __Infer<typeof LastPost>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  senderIdentity: __t.identity(),
  recipientIdentity: __t.option(__t.identity()),
  orgId: __t.option(__t.u64()),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const MonthlyVerificationCap = __t.object("MonthlyVerificationCap", {
  monthKey: __t.string(),
  completedCount: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type MonthlyVerificationCap = __Infer<typeof MonthlyVerificationCap>;

export const MyFeed = __t.object("MyFeed", {});
export type MyFeed = __Infer<typeof MyFeed>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  recipientIdentity: __t.identity(),
  type: __t.string(),
  fromIdentity: __t.option(__t.identity()),
  orgId: __t.option(__t.u64()),
  message: __t.string(),
  createdAt: __t.timestamp(),
  resolved: __t.bool(),
});
export type Notification = __Infer<typeof Notification>;

export const OrgMemberRequest = __t.object("OrgMemberRequest", {
  id: __t.u64(),
  orgId: __t.u64(),
  fromIdentity: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type OrgMemberRequest = __Infer<typeof OrgMemberRequest>;

export const Organization = __t.object("Organization", {
  id: __t.u64(),
  name: __t.string(),
  picture: __t.string(),
  city: __t.string(),
  description: __t.string(),
  leaderIdentity: __t.identity(),
  createdAt: __t.timestamp(),
  isPro: __t.bool(),
});
export type Organization = __Infer<typeof Organization>;

export const OrganizationMember = __t.object("OrganizationMember", {
  orgId: __t.u64(),
  memberIdentity: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type OrganizationMember = __Infer<typeof OrganizationMember>;

export const PendingRegistration = __t.object("PendingRegistration", {
  identity: __t.identity(),
  email: __t.string(),
  fullName: __t.string(),
  legalName: __t.string(),
  city: __t.string(),
  description: __t.string(),
  phoneNumber: __t.string(),
  diditSessionId: __t.string(),
  createdAt: __t.timestamp(),
  profilePicture: __t.string(),
  diditSelfieImage: __t.string(),
});
export type PendingRegistration = __Infer<typeof PendingRegistration>;

export const PushSubscription = __t.object("PushSubscription", {
  identity: __t.identity(),
  endpoint: __t.string(),
  p256Dh: __t.string(),
  auth: __t.string(),
  createdAt: __t.timestamp(),
});
export type PushSubscription = __Infer<typeof PushSubscription>;

export const StoryPost = __t.object("StoryPost", {
  id: __t.u64(),
  profileOwnerIdentity: __t.identity(),
  posterIdentity: __t.identity(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  createdAt: __t.timestamp(),
  actingAsOrgId: __t.option(__t.u64()),
});
export type StoryPost = __Infer<typeof StoryPost>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  email: __t.string(),
  fullName: __t.string(),
  city: __t.string(),
  description: __t.string(),
  createdAt: __t.timestamp(),
  phoneNumber: __t.string(),
  phoneVerified: __t.bool(),
  profilePicture: __t.string(),
  isPro: __t.bool(),
  manuallyCreated: __t.bool(),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const VerificationRateLimit = __t.object("VerificationRateLimit", {
  identity: __t.identity(),
  attemptCount: __t.u32(),
  lastAttemptAt: __t.timestamp(),
  firstAttemptAt: __t.timestamp(),
});
export type VerificationRateLimit = __Infer<typeof VerificationRateLimit>;

export const VerifiedIdentity = __t.object("VerifiedIdentity", {
  identity: __t.identity(),
  legalName: __t.string(),
  diditVerified: __t.bool(),
  diditSelfieImage: __t.string(),
});
export type VerifiedIdentity = __Infer<typeof VerifiedIdentity>;

