// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const FeedPosition = __t.object("FeedPosition", {
  identity: __t.identity(),
  lastReadAt: __t.timestamp(),
  lastFeedLoadAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FeedPosition = __Infer<typeof FeedPosition>;

export const FeedStory = __t.object("FeedStory", {
  id: __t.u64(),
  profileOwnerIdentity: __t.identity(),
  posterIdentity: __t.identity(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  createdAt: __t.timestamp(),
  posterName: __t.string(),
  posterPicture: __t.string(),
  profileOwnerName: __t.string(),
  profileOwnerPicture: __t.string(),
});
export type FeedStory = __Infer<typeof FeedStory>;

export const Following = __t.object("Following", {
  followerIdentity: __t.identity(),
  followingIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Following = __Infer<typeof Following>;

export const LastPost = __t.object("LastPost", {
  posterIdentity: __t.identity(),
  profileOwnerIdentity: __t.identity(),
  lastPostedAt: __t.timestamp(),
});
export type LastPost = __Infer<typeof LastPost>;

export const MyFeed = __t.object("MyFeed", {});
export type MyFeed = __Infer<typeof MyFeed>;

export const PushSubscription = __t.object("PushSubscription", {
  identity: __t.identity(),
  endpoint: __t.string(),
  p256Dh: __t.string(),
  auth: __t.string(),
  createdAt: __t.timestamp(),
});
export type PushSubscription = __Infer<typeof PushSubscription>;

export const StoryPost = __t.object("StoryPost", {
  id: __t.u64(),
  profileOwnerIdentity: __t.identity(),
  posterIdentity: __t.identity(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  createdAt: __t.timestamp(),
});
export type StoryPost = __Infer<typeof StoryPost>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  email: __t.string(),
  fullName: __t.string(),
  profilePicture: __t.string(),
  city: __t.string(),
  description: __t.string(),
  createdAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

