// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CheckDiditVerificationProcedure from "../check_didit_verification_procedure";
import * as CreateVerifiedProfileProcedure from "../create_verified_profile_procedure";
import * as InitiateDiditVerificationProcedure from "../initiate_didit_verification_procedure";

export type CheckDiditVerificationArgs = __Infer<typeof CheckDiditVerificationProcedure.params>;
export type CheckDiditVerificationResult = __Infer<typeof CheckDiditVerificationProcedure.returnType>;
export type CreateVerifiedProfileArgs = __Infer<typeof CreateVerifiedProfileProcedure.params>;
export type CreateVerifiedProfileResult = __Infer<typeof CreateVerifiedProfileProcedure.returnType>;
export type InitiateDiditVerificationArgs = __Infer<typeof InitiateDiditVerificationProcedure.params>;
export type InitiateDiditVerificationResult = __Infer<typeof InitiateDiditVerificationProcedure.returnType>;

