// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateProfileReducer from "../create_profile_reducer";
import CreateStoryPostReducer from "../create_story_post_reducer";
import DeleteStoryPostReducer from "../delete_story_post_reducer";
import FollowReducer from "../follow_reducer";
import OnConnectReducer from "../on_connect_reducer";
import OnDisconnectReducer from "../on_disconnect_reducer";
import RefreshFeedReducer from "../refresh_feed_reducer";
import RegisterPushSubscriptionReducer from "../register_push_subscription_reducer";
import UnfollowReducer from "../unfollow_reducer";
import UnregisterPushSubscriptionReducer from "../unregister_push_subscription_reducer";
import UpdateFeedScrollPositionReducer from "../update_feed_scroll_position_reducer";
import UpdateProfileReducer from "../update_profile_reducer";

export type CreateProfileParams = __Infer<typeof CreateProfileReducer>;
export type CreateStoryPostParams = __Infer<typeof CreateStoryPostReducer>;
export type DeleteStoryPostParams = __Infer<typeof DeleteStoryPostReducer>;
export type FollowParams = __Infer<typeof FollowReducer>;
export type OnConnectParams = __Infer<typeof OnConnectReducer>;
export type OnDisconnectParams = __Infer<typeof OnDisconnectReducer>;
export type RefreshFeedParams = __Infer<typeof RefreshFeedReducer>;
export type RegisterPushSubscriptionParams = __Infer<typeof RegisterPushSubscriptionReducer>;
export type UnfollowParams = __Infer<typeof UnfollowReducer>;
export type UnregisterPushSubscriptionParams = __Infer<typeof UnregisterPushSubscriptionReducer>;
export type UpdateFeedScrollPositionParams = __Infer<typeof UpdateFeedScrollPositionReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;

