// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendRequestReducer from "../accept_friend_request_reducer";
import AcceptOrgMemberReducer from "../accept_org_member_reducer";
import AdminDeleteProfileReducer from "../admin_delete_profile_reducer";
import AdminSetBirthdayReducer from "../admin_set_birthday_reducer";
import AdminSetProReducer from "../admin_set_pro_reducer";
import AdminUpdateProfileReducer from "../admin_update_profile_reducer";
import CancelFriendRequestReducer from "../cancel_friend_request_reducer";
import ClaimProfileReducer from "../claim_profile_reducer";
import CreateOrganizationReducer from "../create_organization_reducer";
import CreateProfileReducer from "../create_profile_reducer";
import CreateStoryPostReducer from "../create_story_post_reducer";
import DeclineFriendRequestReducer from "../decline_friend_request_reducer";
import DeclineOrgMemberReducer from "../decline_org_member_reducer";
import DeleteStoryPostReducer from "../delete_story_post_reducer";
import DemoteCoLeaderReducer from "../demote_co_leader_reducer";
import FollowReducer from "../follow_reducer";
import JitterOrgToApproxReducer from "../jitter_org_to_approx_reducer";
import JitterToApproxReducer from "../jitter_to_approx_reducer";
import ManualCreateProfileReducer from "../manual_create_profile_reducer";
import PromoteToCoLeaderReducer from "../promote_to_co_leader_reducer";
import RefreshFeedReducer from "../refresh_feed_reducer";
import RegisterPushSubscriptionReducer from "../register_push_subscription_reducer";
import RemoveOrgMemberReducer from "../remove_org_member_reducer";
import ResolveNotificationReducer from "../resolve_notification_reducer";
import SendDirectMessageReducer from "../send_direct_message_reducer";
import SendFriendRequestReducer from "../send_friend_request_reducer";
import SendOrgMemberRequestReducer from "../send_org_member_request_reducer";
import SendOrgMessageReducer from "../send_org_message_reducer";
import TransferLeadershipReducer from "../transfer_leadership_reducer";
import UnfollowReducer from "../unfollow_reducer";
import UnfriendReducer from "../unfriend_reducer";
import UnregisterPushSubscriptionReducer from "../unregister_push_subscription_reducer";
import UpdateFeedScrollPositionReducer from "../update_feed_scroll_position_reducer";
import UpdateLocationReducer from "../update_location_reducer";
import UpdateOrgLocationReducer from "../update_org_location_reducer";
import UpdateOrganizationReducer from "../update_organization_reducer";
import UpdateProfileReducer from "../update_profile_reducer";
import UpgradeToProReducer from "../upgrade_to_pro_reducer";

export type AcceptFriendRequestParams = __Infer<typeof AcceptFriendRequestReducer>;
export type AcceptOrgMemberParams = __Infer<typeof AcceptOrgMemberReducer>;
export type AdminDeleteProfileParams = __Infer<typeof AdminDeleteProfileReducer>;
export type AdminSetBirthdayParams = __Infer<typeof AdminSetBirthdayReducer>;
export type AdminSetProParams = __Infer<typeof AdminSetProReducer>;
export type AdminUpdateProfileParams = __Infer<typeof AdminUpdateProfileReducer>;
export type CancelFriendRequestParams = __Infer<typeof CancelFriendRequestReducer>;
export type ClaimProfileParams = __Infer<typeof ClaimProfileReducer>;
export type CreateOrganizationParams = __Infer<typeof CreateOrganizationReducer>;
export type CreateProfileParams = __Infer<typeof CreateProfileReducer>;
export type CreateStoryPostParams = __Infer<typeof CreateStoryPostReducer>;
export type DeclineFriendRequestParams = __Infer<typeof DeclineFriendRequestReducer>;
export type DeclineOrgMemberParams = __Infer<typeof DeclineOrgMemberReducer>;
export type DeleteStoryPostParams = __Infer<typeof DeleteStoryPostReducer>;
export type DemoteCoLeaderParams = __Infer<typeof DemoteCoLeaderReducer>;
export type FollowParams = __Infer<typeof FollowReducer>;
export type JitterOrgToApproxParams = __Infer<typeof JitterOrgToApproxReducer>;
export type JitterToApproxParams = __Infer<typeof JitterToApproxReducer>;
export type ManualCreateProfileParams = __Infer<typeof ManualCreateProfileReducer>;
export type PromoteToCoLeaderParams = __Infer<typeof PromoteToCoLeaderReducer>;
export type RefreshFeedParams = __Infer<typeof RefreshFeedReducer>;
export type RegisterPushSubscriptionParams = __Infer<typeof RegisterPushSubscriptionReducer>;
export type RemoveOrgMemberParams = __Infer<typeof RemoveOrgMemberReducer>;
export type ResolveNotificationParams = __Infer<typeof ResolveNotificationReducer>;
export type SendDirectMessageParams = __Infer<typeof SendDirectMessageReducer>;
export type SendFriendRequestParams = __Infer<typeof SendFriendRequestReducer>;
export type SendOrgMemberRequestParams = __Infer<typeof SendOrgMemberRequestReducer>;
export type SendOrgMessageParams = __Infer<typeof SendOrgMessageReducer>;
export type TransferLeadershipParams = __Infer<typeof TransferLeadershipReducer>;
export type UnfollowParams = __Infer<typeof UnfollowReducer>;
export type UnfriendParams = __Infer<typeof UnfriendReducer>;
export type UnregisterPushSubscriptionParams = __Infer<typeof UnregisterPushSubscriptionReducer>;
export type UpdateFeedScrollPositionParams = __Infer<typeof UpdateFeedScrollPositionReducer>;
export type UpdateLocationParams = __Infer<typeof UpdateLocationReducer>;
export type UpdateOrgLocationParams = __Infer<typeof UpdateOrgLocationReducer>;
export type UpdateOrganizationParams = __Infer<typeof UpdateOrganizationReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;
export type UpgradeToProParams = __Infer<typeof UpgradeToProReducer>;

